### ISSUE TITLE
Error in import WF attempt

### ISSUE THREAD

**Issue by eddieholeman** [ShepherdDev/rock-misc#10]
I am running Rock v8.4 on both production and sandbox.  I have attempted to export / import 2 different workflows via the Share Workflow tool and am getting similar errors.  I see the following error twice:

Error importing encoded entity: {"EntityType":"Rock.Model.AttributeValue","Guid":"173460c9-e7c2-496f-8d74-7caa420b47df","NewGuid":true,"Properties":{"IsSystem":false,"EntityId":4292,"Value":"False","CreatedDateTime":"2018-11-17T09:11:22.433","ModifiedDateTime":"2018-11-17T09:11:22.433"},"Transforms":{},"References":[{"Property":"AttributeId","EntityType":"Rock.Model.Attribute","Type":1,"Data":"234910f2-a0db-4d7d-baf7-83c880ef30ae"}]}

Attached is the export file.  Thanks for any help on this.  Love the feature, but hoping to find a way to get this working in my environment.

[Copy Newsletter_201811190835.zip](https://github.com/ShepherdDev/rock-misc/files/2596401/Copy.Newsletter_201811190835.zip)

**Comment by cabal95** [comment]
Is this something that worked before upgrading to 8.4, or that just happens to be what you are running on now?

**Comment by eddieholeman** [comment]
Just the version I am on.  I just wrote to the workflow and wanted to move
it from one server to the other.  So, nothing I have asked about before.

**Comment by cabal95** [comment]
Okay just checking. I'll take a look, though it may not be until after this week before I can get to it.

**Comment by eddieholeman** [comment]
Thanks for your help.

**Comment by cabal95** [comment]
Hey Eddie, as far as I can tell, you might have two different versions of the ShareWorkflow block installed. Specifically, it looks like maybe an older version installed on the exporting Rock instance and the newer version installed on the importing Rock instance. All the content in the workflow JSON file looks like it's from an older version. The new version expects data in a certain format, which it isn't currently in.

**Comment by eddieholeman** [comment]
Daniel, I have replaced the block files on both production and sandbox with the latest version.  I export from Production and then Upload to Sandbox.  No errors, but I cannot find the imported workflow.  Here is the response to the Import:

`Created: Rock.Model.WorkflowType, 3b054467-a7fc-4b71-b15f-5e2297aeec66
Created: Rock.Model.WorkflowActivityType, 1ec44399-6203-4a65-9478-4d6a294915fc
Created: Rock.Model.WorkflowActionType, b8e2324a-204b-49aa-9173-467a384aa5cb
Error importing encoded entity: {"EntityType":"Rock.Model.AttributeValue","Guid":"52be0998-04d6-440a-ae4d-80827f865187","NewGuid":true,"Properties":{"IsSystem":false,"EntityId":4322,"Value":"b7b28d40-3d00-47a9-a5d9-a985b3b1b64a","CreatedDateTime":"2018-11-19T12:31:34.59","ModifiedDateTime":"2018-11-19T12:31:34.59"},"Transforms":{},"References":[{"Property":"AttributeId","EntityType":"Rock.Model.Attribute","Type":1,"Data":"6af13055-0af4-4eb9-9722-0cc02de502fb"}]}
Error importing encoded entity: {"EntityType":"Rock.Model.AttributeValue","Guid":"52be0998-04d6-440a-ae4d-80827f865187","NewGuid":true,"Properties":{"IsSystem":false,"EntityId":4322,"Value":"b7b28d40-3d00-47a9-a5d9-a985b3b1b64a","CreatedDateTime":"2018-11-19T12:31:34.59","ModifiedDateTime":"2018-11-19T12:31:34.59"},"Transforms":{},"References":[{"Property":"AttributeId","EntityType":"Rock.Model.Attribute","Type":1,"Data":"6af13055-0af4-4eb9-9722-0cc02de502fb"}]}`

What am I missing? Where could it be?

**Comment by cabal95** [comment]
Sorry, I'm really not sure then. It still seems to be generating an "old style" format. The primary difference is that the `References` array should contain an entry for `EntityId`, but it doesn't. If you are for sure using the latest version then there might be something in the workflow / system / Rock version that is causing issues - but I don't know what those could be.

**Comment by eddieholeman** [comment]
Daniel, to be clear, here is the link I used to download your share workflow plugin.  https://github.com/ShepherdDev/rock-misc/releases/tag/shareworkflow-0.0.1  Is this the correct location?

**Comment by cabal95** [comment]
You can try grabbing the two ShareWorkflow files from here: https://github.com/ShepherdDev/rock-misc/tree/master/Controls

But I believe they are the same as that zip file. As I said, it is certainly possible that something about your Rock system or Workflow itself is causing issues somehow and not allowing the proper code to run during export.

**Comment by eddieholeman** [comment]
I tried grabbing those 2 ShareWorkflow files and placing them in both my production and sandbox environments.  I then re-ran the export/import and no change. No error, but still isn't creating the workflow. Must be as you said.  :-(

**Comment by tedinedh** [comment]
Similar issue(I think)  workflow does not show up after import-  Created: Rock.Model.WorkflowType, afa837cd-6b70-434f-a08d-8752a529e0d0
Created: Rock.Model.WorkflowActivityType, 017306ab-01b5-4091-9442-c068283325ac
Created: Rock.Model.WorkflowActionForm, c3a03bf6-92f1-47e6-ae6b-790645535089
Created: Rock.Model.Attribute, df8dc773-c2fc-4edd-bf00-0b410a602102
Created: Rock.Model.AttributeQualifier, 11fc97a5-acec-48bb-8deb-9304ad4396c9
Created: Rock.Model.AttributeQualifier, 80b2e60f-ed84-4fda-80e6-91a266e0ccff
Created: Rock.Model.AttributeQualifier, ca9e9246-e4ad-4e32-932a-b47b400bee66
Created: Rock.Model.WorkflowActionFormAttribute, debdc3fe-d7fd-4992-b65d-54526f2ea860
Created: Rock.Model.Attribute, c8af80c0-156f-413a-b3e2-674f68e7c3d1
Created: Rock.Model.AttributeQualifier, 0df168b6-25c7-4364-a943-37673b514d4c
Created: Rock.Model.AttributeQualifier, b790696c-ab77-4079-b7ac-7a645f67e666
Created: Rock.Model.AttributeQualifier, c2cd6b58-a578-42ca-b83c-3e1f59150172
Created: Rock.Model.AttributeQualifier, cb03a719-f779-4e36-bbe0-dc3a879d2d20
Created: Rock.Model.WorkflowActionFormAttribute, 7f5dbcd4-bbf4-423f-8337-23b4bb1304e8
Created: Rock.Model.Attribute, 82cf2531-13ca-4bde-8a7a-f7e5f1f58b40
Created: Rock.Model.WorkflowActionFormAttribute, 2fa3c90e-9b5b-41ac-8998-a298f0750b41
Created: Rock.Model.Attribute, 765ed567-ab4c-4414-aea4-8329998cdfbf
Created: Rock.Model.AttributeQualifier, b0ae1ce7-69de-421a-943f-261b43e4240c
Created: Rock.Model.AttributeQualifier, a91c11a8-b92f-4528-8c7e-917131023a4d
Created: Rock.Model.AttributeQualifier, fd60ee55-f481-4528-b979-21fc6b655c00
Created: Rock.Model.AttributeQualifier, 9c19e327-a0c9-4f15-8184-9f8e4876b9ad
Created: Rock.Model.WorkflowActionFormAttribute, bcc37665-bf9e-4fa3-b7b1-dabbda23c597
Created: Rock.Model.Attribute, 7b8cce32-ac1c-45d0-afb9-0a8bdbd2c146
Created: Rock.Model.AttributeQualifier, 6080d213-ad0a-4577-ba58-53d8f9124fe6
Created: Rock.Model.AttributeQualifier, c400a53e-0e3b-4242-81b4-aaf67a1dd967
Created: Rock.Model.AttributeQualifier, b4700f57-b9fe-4746-860a-a92d9f5a5c3f
Created: Rock.Model.WorkflowActionFormAttribute, 60298672-eddf-4302-a341-c99378823f8e
Created: Rock.Model.Attribute, fbb416e1-e78f-4afe-80f0-6b2d49bf7dda
Created: Rock.Model.AttributeQualifier, e163025e-e6cb-44f3-94c0-a412ff324409
Created: Rock.Model.AttributeQualifier, f3203c3a-6551-4fe5-8015-9c57e3dff4e4
Created: Rock.Model.AttributeQualifier, e91f0145-a641-4961-b7de-9d7a1bca84fe
Created: Rock.Model.WorkflowActionFormAttribute, 6f4d6264-0afb-47d7-8c38-6c56c9787123
Created: Rock.Model.Attribute, 2d8d1e82-320a-4ac3-a6ca-d37432c0e14d
Created: Rock.Model.AttributeQualifier, c9a49abc-d027-4cb9-9646-ca5a69afbf54
Created: Rock.Model.AttributeQualifier, 160cb0c6-76d2-431b-b27f-44f332ea2175
Created: Rock.Model.AttributeQualifier, 1fea72e2-c462-4564-a7a6-8dcc70471a3c
Created: Rock.Model.WorkflowActionFormAttribute, ac3a38fe-f186-4bff-9b4f-ea7a0d8ca6b1
Created: Rock.Model.Attribute, eed407ad-06aa-41c4-929c-1b90932c786e
Created: Rock.Model.AttributeQualifier, e42bb48e-5760-44cb-aa23-bde219bf6060
Created: Rock.Model.AttributeQualifier, 4172900a-b8ff-4f1d-b95a-782b50577bf9
Created: Rock.Model.AttributeQualifier, 75498424-093f-4642-9bb8-6df1a5ffd8cb
Created: Rock.Model.AttributeQualifier, 2ddae704-5f8c-44d7-b58d-049af8f71916
Created: Rock.Model.AttributeQualifier, 3f9cf26e-5c38-40c2-b145-33eca2c2410b
Created: Rock.Model.WorkflowActionFormAttribute, 3b129662-8eb3-43da-8a26-d4bcf4c2a3a2
Created: Rock.Model.Attribute, 71d6aee2-643b-47db-ad59-9b582079f2a0
Created: Rock.Model.AttributeQualifier, c588c100-d990-4e47-bc04-21c241be8853
Created: Rock.Model.AttributeQualifier, 07c11c9a-47d9-4cc2-9e19-5a511b079357
Created: Rock.Model.AttributeQualifier, 31e377ab-403b-47af-a97a-f10bd79f8e80
Created: Rock.Model.WorkflowActionFormAttribute, 741a6efa-118b-4816-aaf1-226829373d5a
Created: Rock.Model.Attribute, 19f4b745-7455-496e-a91a-820e2bb32691
Created: Rock.Model.AttributeQualifier, e3faa991-7168-46bd-a2b7-e4cf496666f5
Created: Rock.Model.AttributeQualifier, c290697c-65bf-431b-9f6a-048edefbdeda
Created: Rock.Model.AttributeQualifier, fb52b319-01d8-4338-b103-bcbc81894ff0
Created: Rock.Model.WorkflowActionFormAttribute, 95dbdf9a-2cb4-432d-a0e1-1f4f06edebe7
Created: Rock.Model.Attribute, 3d2ea0a2-b00a-4211-9f2f-a934f03cde26
Created: Rock.Model.WorkflowActionFormAttribute, d8dcca62-d8b8-4572-a1e0-87a324d59b38
Created: Rock.Model.Attribute, 4668c619-3904-40ff-8a6d-88f774f0073a
Created: Rock.Model.AttributeQualifier, 86a8d20e-6a93-4b25-b234-57581d9398c8
Created: Rock.Model.WorkflowActionFormAttribute, d206ede6-5e08-447b-90f6-31bc07cb3760
Created: Rock.Model.Attribute, 516c311c-903d-4852-8dfb-c6af8639ef0f
Created: Rock.Model.AttributeQualifier, b3c1f9a8-4c97-4d25-98f3-c959776bbadc
Created: Rock.Model.AttributeQualifier, 4c3f58c3-bbd9-40f6-8bb0-8b6f9fa920aa
Created: Rock.Model.AttributeQualifier, a6cc1cbc-0def-4bdc-aa60-5ae809ba5290
Created: Rock.Model.WorkflowActionFormAttribute, 66be92d4-5f4e-4db9-ab86-bde70cd20c37
Created: Rock.Model.Attribute, c472b839-3ee9-4b19-b7f3-6a0350fcbbfd
Created: Rock.Model.AttributeQualifier, 1677d2ec-9079-400b-8c28-708f394614c3
Created: Rock.Model.AttributeQualifier, 5e54a023-d40b-46cb-85b6-cd57f91acbc1
Created: Rock.Model.AttributeQualifier, 5cbf103c-7c0e-4e21-a6a1-e34818c2bbee
Created: Rock.Model.WorkflowActionFormAttribute, 397b63e6-60c2-4675-a4f6-132636c5de87
Created: Rock.Model.Attribute, 40d3475a-5519-44a5-8c69-405f73b08a28
Created: Rock.Model.AttributeQualifier, 0d84e7df-b6ea-4612-8a50-fe09164747b2
Created: Rock.Model.AttributeQualifier, f60a2837-55e8-4cac-9933-58996928e7ee
Created: Rock.Model.AttributeQualifier, 01fcf795-634e-4d90-bd31-8ff4de7f390b
Created: Rock.Model.WorkflowActionFormAttribute, 04768fe9-1ee8-4ea9-8169-d5a83a3c8275
Created: Rock.Model.Attribute, 974dffe0-39ed-4595-8aa4-c2bf671427cd
Created: Rock.Model.AttributeQualifier, 3383d6cd-a15e-4dac-bf15-ef9d0c2d3aa2
Created: Rock.Model.AttributeQualifier, 19e59c48-51c1-4821-a849-c2c1fbd89d04
Created: Rock.Model.AttributeQualifier, 0d82b3c7-a95a-4116-9c63-6b8384740405
Created: Rock.Model.WorkflowActionFormAttribute, 6e4a2325-7ce7-452b-b7b8-eeda4277728f
Created: Rock.Model.Attribute, 62c9ce95-3ea9-482d-b3a9-cee6a2a72db6
Created: Rock.Model.AttributeQualifier, a227a33c-9b73-481d-ad90-1f5df8b3473e
Created: Rock.Model.AttributeQualifier, 419abb0c-14bd-46a0-8abb-636b2e0c761a
Created: Rock.Model.AttributeQualifier, 43ce1dcd-18f6-41e1-945c-5a21b3adf1bf
Created: Rock.Model.WorkflowActionFormAttribute, 857234f1-3fa9-4e27-97f7-2603bb804be4
Created: Rock.Model.Attribute, c6635671-5324-41ef-abb1-15f863490cd0
Created: Rock.Model.AttributeQualifier, 5ad7bede-a6e0-41f7-8d36-87ee906e76ae
Created: Rock.Model.AttributeQualifier, 00bc2d5d-0f58-4156-9892-b5b9de2ae795
Created: Rock.Model.AttributeQualifier, 26262307-c799-44cc-b7b2-f76aac7c844d
Created: Rock.Model.WorkflowActionFormAttribute, 58f9bc03-fbe5-4fa4-8842-4d5b440d685d
Created: Rock.Model.Attribute, 35c2eb0a-0707-4dfd-9b56-a94f35e2865d
Created: Rock.Model.AttributeQualifier, 784240fa-f9dd-4fda-b48e-823410bf4adf
Created: Rock.Model.AttributeQualifier, d32bff7d-a2eb-42b7-8397-fcc5e0bc455f
Created: Rock.Model.AttributeQualifier, d5cb62a2-e459-477c-b67f-6b8f0a8b2724
Created: Rock.Model.WorkflowActionFormAttribute, 10902ea3-4825-44de-b48f-b0aa237adc52
Created: Rock.Model.Attribute, 844555d3-8260-4c92-92d6-e6e11098920f
Created: Rock.Model.AttributeQualifier, 270e37f0-3aad-4ca6-861c-81661f9ae939
Created: Rock.Model.WorkflowActionFormAttribute, d0d731d9-bcd6-4b5a-b7f0-9ce19b1b524c
Created: Rock.Model.Attribute, 040ccc05-296f-42d6-a707-20f4eb44ad15
Created: Rock.Model.AttributeQualifier, 0a66f65a-a5ca-4fdc-851a-cebce8e8c1ce
Created: Rock.Model.AttributeQualifier, dbcbbdd3-3038-4326-83d3-dee976fa2003
Created: Rock.Model.AttributeQualifier, 84262655-9572-46ff-8c80-5048e7cd1582
Created: Rock.Model.WorkflowActionFormAttribute, 93813654-be02-430e-ae3b-c75d8f375c87
Created: Rock.Model.Attribute, d30fcc1f-c42c-4aca-8696-94b15b9effbe
Created: Rock.Model.AttributeQualifier, 8d382eac-372b-416e-9819-2476bdd99312
Created: Rock.Model.AttributeQualifier, 9e1bf34a-17ea-4db1-9ea1-b7cc0c497d6f
Created: Rock.Model.AttributeQualifier, 947b80b5-d2a4-4239-959b-ad3798f1c5bc
Created: Rock.Model.WorkflowActionFormAttribute, 64770d6c-7faa-4f2c-b474-9cd60bf472bc
Created: Rock.Model.Attribute, 3eb26873-232b-4fbb-b055-724fc9d8da86
Created: Rock.Model.AttributeQualifier, a367d7a4-1c06-444b-afef-7ea7ad7b2abd
Created: Rock.Model.AttributeQualifier, 693081db-4a46-4cd9-84ae-0b6164c3929f
Created: Rock.Model.AttributeQualifier, 19888fc8-a9be-4a63-b440-a96e561dd1ed
Created: Rock.Model.WorkflowActionFormAttribute, 80f51ee9-9dde-4054-bec7-0f97982d7dad
Created: Rock.Model.Attribute, 70406ab6-df98-4a76-a177-736d29ea8308
Created: Rock.Model.AttributeQualifier, c1e65de1-f822-4bc2-8862-5ad49215d32b
Created: Rock.Model.AttributeQualifier, d0d0c6d4-c419-4c52-92b7-ebd21101d1f6
Created: Rock.Model.AttributeQualifier, fabdf3e5-61da-4e86-a339-a32725c531f2
Created: Rock.Model.WorkflowActionFormAttribute, 95c55586-76ae-420e-9d91-fdabefc0ab11
Created: Rock.Model.Attribute, 7dd647ad-266c-4746-94e9-f4a89998e751
Created: Rock.Model.AttributeQualifier, cac3c16c-e169-427b-9495-5e22b0143565
Created: Rock.Model.AttributeQualifier, adc7a99f-99fb-44ea-960a-fb53f798ff39
Created: Rock.Model.AttributeQualifier, f3707a67-ddf6-4c83-8d24-1691b7350c61
Created: Rock.Model.WorkflowActionFormAttribute, 8d34f60f-a935-48bf-915d-ce7773800b4a
Created: Rock.Model.Attribute, d1e5ee4a-e133-46ae-8b77-2a365b958663
Created: Rock.Model.AttributeQualifier, e857dbce-2ba0-4919-873d-eabc9bfa2140
Created: Rock.Model.AttributeQualifier, 0fe84bb2-0e46-4456-b925-e0fc2daf54c3
Created: Rock.Model.AttributeQualifier, c44ca3f0-3dab-4f6e-bb9d-f02a6161725e
Created: Rock.Model.WorkflowActionFormAttribute, 362bc99c-fd8a-45db-93fd-df2115ffe418
Created: Rock.Model.Attribute, 0e71f8c1-b75c-4b89-82c7-b041695ea938
Created: Rock.Model.AttributeQualifier, b0ee0553-e509-4234-a526-b67d88402727
Created: Rock.Model.AttributeQualifier, 8129e730-0a5a-45c8-9f94-889faea5e25e
Created: Rock.Model.AttributeQualifier, 17792060-f3cb-4c2a-8a41-7d85b58265a6
Created: Rock.Model.AttributeQualifier, 3112d1e4-cb0b-481d-b07e-88a13c5d84ec
Created: Rock.Model.AttributeQualifier, a60218a4-7965-4b7a-a51e-8c8a8c3d5e70
Created: Rock.Model.WorkflowActionFormAttribute, 340708a8-5c8c-44f2-9be8-090e80e62883
Created: Rock.Model.Attribute, 4d252224-8ee6-4ab3-a43a-bd68aa8e70cd
Created: Rock.Model.AttributeQualifier, caa38096-a4ab-4adb-93ca-83b6a9c32e10
Created: Rock.Model.AttributeQualifier, d3d0c7a9-1d23-4d2a-b847-04795fd8f60d
Created: Rock.Model.AttributeQualifier, 4afc0402-1cfa-48b7-a353-b58a51e71638
Created: Rock.Model.WorkflowActionFormAttribute, bccd280a-7117-43af-ba54-7b2b063e2c12
Created: Rock.Model.Attribute, 3874698a-bfcf-407e-ac7f-ebd1f679ea5b
Created: Rock.Model.AttributeQualifier, 607f4990-9bf5-4d35-bcdc-48a0aae662aa
Created: Rock.Model.AttributeQualifier, 50740863-af56-465b-a26c-1de57a26fc09
Created: Rock.Model.AttributeQualifier, 614a98b5-6c0b-43f0-b6a8-e386b9b0f816
Created: Rock.Model.WorkflowActionFormAttribute, e4059b00-a52d-434b-8677-2000a88425dd
Created: Rock.Model.WorkflowActionType, c4d3cf59-b7ce-4eb3-8f81-0d8f1193ea5d
Error importing encoded entity: {"EntityType":"Rock.Model.AttributeValue","Guid":"38778286-179c-481e-a7bc-bfc547c4beab","NewGuid":true,"Properties":{"IsSystem":false,"EntityId":1449,"Value":"False","CreatedDateTime":"2019-05-31T09:47:42.243","ModifiedDateTime":"2019-05-31T09:47:42.243"},"Transforms":{},"References":[{"Property":"AttributeId","EntityType":"Rock.Model.Attribute","Type":1,"Data":"234910f2-a0db-4d7d-baf7-83c880ef30ae"}]}
Error importing encoded entity: {"EntityType":"Rock.Model.AttributeValue","Guid":"38778286-179c-481e-a7bc-bfc547c4beab","NewGuid":true,"Properties":{"IsSystem":false,"EntityId":1449,"Value":"False","CreatedDateTime":"2019-05-31T09:47:42.243","ModifiedDateTime":"2019-05-31T09:47:42.243"},"Transforms":{},"References":[{"Property":"AttributeId","EntityType":"Rock.Model.Attribute","Type":1,"Data":"234910f2-a0db-4d7d-baf7-83c880ef30ae"}]}

**Comment by cabal95** [comment]
After some investigating on chat (after which I forgot to update this issue), the core problem is a bug that was introduced in Rock 8.0 and won't be fixed until 9.0 (which is has just entered beta testing). Rock 8.0 made an (unintentional) change that broke the way Rock loads certain DLLs which caused the export and import to not process correctly.
