### ISSUE TITLE
Workflow Export Preview Error

### ISSUE THREAD

**Issue by JRichmond27** [ShepherdDev/rock-misc#11]
An error occurs if a workflow category is accidentally selected instead of a type and then Export or Preview is clicked...

> NullReferenceException in App_Web_psnwcqdr
> 
> Message
> Object reference not set to an instance of an object.
> 
>  Stack Trace
> at RockWeb.Plugins.com_shepherdchurch.Misc.Export.Helper.EnqueueEntity(IEntity entity, EntityPath path, Boolean entityIsCritical, IExporter exporter)
> at RockWeb.Plugins.com_shepherdchurch.Misc.Export.WorkflowTypeExporter.Preview2(WorkflowType entity)
> at RockWeb.Plugins.com_shepherdchurch.Misc.ShareWorkflow.btnPreview_Click(Object sender, EventArgs e)
> at System.Web.UI.WebControls.Button.OnClick(EventArgs e)
> at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
> at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by cabal95** [comment]
This should be fixed in v9, which includes the workflow import/export internally.
